[splits.ReadBlockHDF5]
expected = [ "key" ]
partition_memory_usage = "part"
scale_by = 2
views = false
required = { name = "Distributing", distribution = "blocked", id = "!" }
locations = [ {name = "Remote", format = "hdf5"} ]

# These were previously scaled_by = 9 but reduced to 4 because it seemed to
# be causing unnecessary batched I/O and because GC should take care of the extra allocations.

[splits.ReadGroupHDF5]
expected = [ "key", "divisions" ]
partition_memory_usage = "part"
scale_by = 4
views = false
required = { name = "Distributing", distribution = "grouped", id = "!" }
default = { rev = false }
locations = [ {name = "Remote", format = "hdf5"} ]

[splits.CopyFromHDF5]
partition_memory_usage = "all"
scale_by = 2
views = false
required = { name = "Replicating", dividing = false }
locations = [ {name = "Remote", format = "hdf5"} ]

[merges.WriteHDF5]
partition_memory_usage = "part"
scale_by = 1
views = false
required = { name = "Distributing" }
locations = [ {name = "Remote", format = "hdf5"} ]

[merges.CopyToHDF5]
partition_memory_usage = "all"
scale_by = 1
views = false
required = { name = "Replicating", replication = "all" }
locations = [ {name = "Remote", format = "hdf5"} ]