[splits.ReadBlockPNG]
expected = [ "key" ]
partition_memory_usage = "part"
scale_by = 2
owns_partitions = false
required = { name = "Distributing", distribution = "blocked", id = "!" }
locations = [ {name = "Remote", format = "png"}, { name = "Disk", datatype = "PNG" } ]

[merges.WritePNG]
partition_memory_usage = "part"
scale_by = 1
owns_partitions = false
required = { name = "Distributing" }
locations = [ {name = "Remote", format = "png"}, { name = "Disk", datatype = "PNG" } ]