name = "BanyanDataFrames"
uuid = "dfdd4555-3ad7-41cc-a503-a251c9c652f9"
authors = ["Banyan <support@banyancomputing.com>"]
version = "0.1.2"

[deps]
Banyan = "706d138b-e922-45b9-a636-baf8ae0d5317"
BanyanArrays = "369465de-032e-4609-9dcf-82b89c370a7b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"

[compat]
Banyan = "0.2.1"
BanyanArrays = "0.1.3"
DataFrames = "1"
Missings = "1"
julia = "1.6"
