name = "BanyanArrays"
uuid = "369465de-032e-4609-9dcf-82b89c370a7b"
authors = ["Banyan <support@banyancomputing.com>"]
version = "0.1.3"

[deps]
Banyan = "706d138b-e922-45b9-a636-baf8ae0d5317"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
Banyan = "0.2.1"
HDF5 = "0.15.5"
julia = "1.6"
