[splits.ReturnNullGrouping]
partition_memory_usage = "none"
scale_by = 0
views = false
locations = [ { datatype = "GroupedDataFrame" } ]

[merges.ReturnNullGrouping]
partition_memory_usage = "none"
scale_by = 0
views = false
locations = [ { datatype = "GroupedDataFrame" } ]

[casts.ReturnNullGroupingConsolidated]
src_expected = [ "key" ]
scale_by_src = 1
scale_by_dst = 3
src_required = { name = "Distributing" }
dst_required = { name = "Replicating", replication = "all" }
locations = [ { datatype = "GroupedDataFrame" } ]

[casts.ReturnNullGroupingRebalanced]
scale_by_src = 1
scale_by_dst = 3
src_required = { name = "Distributing" }
dst_required = { name = "Distributing", distribution = "blocked", balanced = true, id = "!" }
locations = [ { datatype = "GroupedDataFrame" } ]

# ReadBlock

[splits.ReadBlockCSV]
expected = [ "key" ]
partition_memory_usage = "part"
scale_by = 3
views = false
required = { name = "Distributing", distribution = "blocked", id = "!" }
locations = [ { name = "Remote", format = "csv" } ]

[splits.ReadBlockParquet]
expected = [ "key" ]
partition_memory_usage = "part"
scale_by = 3
views = false
required = { name = "Distributing", distribution = "blocked", id = "!" }
locations = [ { name = "Remote", format = "parquet" } ]

[splits.ReadBlockArrow]
expected = [ "key" ]
partition_memory_usage = "part"
scale_by = 3
views = false
required = { name = "Distributing", distribution = "blocked", id = "!" }
locations = [ { name = "Remote", format = "arrow" }, { name = "Disk", datatype = "DataFrame" } ]

# ReadGroup

[splits.ReadGroupCSV]
expected = [ "key", "divisions" ]
partition_memory_usage = "part"
scale_by = 6
views = false
required = { name = "Distributing", distribution = "grouped", id = "!" }
default = { rev = false }
locations = [ { name = "Remote", format = "csv" } ]

[splits.ReadGroupParquet]
expected = [ "key", "divisions" ]
scale_by_num_partitions = false
scale_by = 6
views = false
required = { name = "Distributing", distribution = "grouped", id = "!" }
default = { rev = false }
locations = [ { name = "Remote", format = "parquet" } ]

[splits.ReadGroupArrow]
expected = [ "key", "divisions" ]
scale_by_num_partitions = false
scale_by = 6
views = false
required = { name = "Distributing", distribution = "grouped", id = "!" }
default = { rev = false }
locations = [ { name = "Remote", format = "arrow" }, { name = "Disk", datatype = "DataFrame" } ]

# CopyFrom

[splits.CopyFromCSV]
partition_memory_usage = "all"
scale_by = 3
views = false
required = { name = "Replicating", dividing = false }
locations = [ { name = "Remote", format = "csv" } ]

[splits.CopyFromParquet]
partition_memory_usage = "all"
scale_by = 3
views = false
required = { name = "Replicating", dividing = false }

  [[splits.CopyFromParquet.locations]]
  name = "Remote"
  format = "parquet"

[splits.CopyFromArrow]
partition_memory_usage = "all"
scale_by = 3
views = false
required = { name = "Replicating", dividing = false }
locations = [ { name = "Remote", format = "arrow" }, { name = "Disk", datatype = "DataFrame" } ]

# Write

[merges.WriteCSV]
partition_memory_usage = "part"
scale_by = 0
views = false
required = { name = "Distributing" }
locations = [ { name = "Remote", format = "csv" } ]

[merges.WriteParquet]
partition_memory_usage = "part"
scale_by = 0
views = false
required = { name = "Distributing" }
locations = [ { name = "Remote", format = "parquet" } ]

[merges.WriteArrow]
partition_memory_usage = "part"
scale_by = 0
views = false
required = { name = "Distributing" }
locations = [ { name = "Remote", format = "arrow" }, { name = "Disk", datatype = "DataFrame" } ]

# CopyTo

[merges.CopyToCSV]
partition_memory_usage = "all"
scale_by = 0
views = false
required = { name = "Replicating", replication = "all" }
locations = [ { name = "Remote", format = "csv" } ]

[merges.CopyToParquet]
partition_memory_usage = "all"
scale_by = 0
views = false
required = { name = "Replicating", replication = "all" }
locations = [ { name = "Remote", format = "parquet" } ]

[merges.CopyToArrow]
partition_memory_usage = "all"
scale_by = 0
views = false
required = { name = "Replicating", replication = "all" }
locations = [ { name = "Remote", format = "arrow" }, { name = "Disk", datatype = "DataFrame" } ]

[casts.ConsolidateDataFrame]
src_expected = [ "key" ]
scale_by_src = 1
scale_by_dst = 3
src_required = { name = "Distributing" }
dst_required = { name = "Replicating", replication = "all" }
locations = [ { datatype = "DataFrame" } ]

[casts.RebalanceDataFrame]
scale_by_src = 1
scale_by_dst = 3
src_required = { name = "Distributing" }
dst_required = { name = "Distributing", distribution = "blocked", balanced = true, id = "!" }
locations = [ { datatype = "DataFrame" } ]

[casts.ShuffleDataFrame]
dst_expected = [ "key", "divisions" ]
scale_by_src = 3
scale_by_dst = 3
src_required = { name = "Distributing" }
dst_required = { name = "Distributing", distribution = "grouped", id = "!" }
dst_default = { rev = false }
locations = [ { datatype = "DataFrame"} ]